name: Contracts CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-format:
    name: Lint & Format (contracts)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: contracts/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Solhint
        run: npm run lint:sol
      - name: Prettier check
        run: npm run format:check

  build:
    name: Compile (contracts)
    runs-on: ubuntu-latest
    needs: [lint-format]
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: contracts/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Compile
        run: npm run compile

  test-coverage:
    name: Test & Coverage (contracts)
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: contracts/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm test
      - name: Coverage
        run: npm run coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: solidity-coverage
          path: contracts/coverage
          if-no-files-found: warn

